"use client";

import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import CategoryFormModal from "./category-form-modal";

export type Category = { id:string; name:string; description:string|null; is_active:boolean };
type ModalState = {mode:"create"}|{mode:"edit";category:Category}|null;
function gradient(name:string){const p=["from-blue-500 to-cyan-400","from-violet-500 to-fuchsia-400","from-emerald-500 to-teal-400","from-amber-500 to-orange-400","from-rose-500 to-pink-400","from-indigo-500 to-purple-400"];let h=0;for(let i=0;i<name.length;i++)h=(h*31+name.charCodeAt(i))>>>0;return p[h%p.length]}

export default function CategoriesClient({initialCategories,counts={},embedded=false}:{initialCategories:Category[];counts?:Record<string,number>;embedded?:boolean}){
 const [categories,setCategories]=useState(initialCategories); const [q,setQ]=useState(""); const [status,setStatus]=useState<"all"|"active"|"inactive">("all"); const [modal,setModal]=useState<ModalState>(null); const [busy,setBusy]=useState<string|null>(null); const supabase=createClient();
 const filtered=useMemo(()=>{const n=q.trim().toLowerCase();return categories.filter(c=>(status==="all"||(status==="active"?c.is_active:!c.is_active))&&(!n||c.name.toLowerCase().includes(n)||String(c.description??"").toLowerCase().includes(n)))},[categories,q,status]);
 const stats=useMemo(()=>({total:categories.length,active:categories.filter(c=>c.is_active).length,items:Object.values(counts).reduce((a,b)=>a+b,0)}),[categories,counts]);
 async function save(input:{name:string;description:string},category?:Category){if(category){const{error}=await supabase.from("categories").update(input).eq("id",category.id);if(error)return alert(error.message);setCategories(p=>p.map(c=>c.id===category.id?{...c,...input}:c))}else{const{data,error}=await supabase.from("categories").insert({...input,is_active:true}).select().single();if(error)return alert(error.message);setCategories(p=>[...p,data as Category])}setModal(null)}
 async function deactivate(id:string){setBusy(id);const{error}=await supabase.from("categories").update({is_active:false}).eq("id",id);setBusy(null);if(error)return alert(error.message);setCategories(p=>p.map(c=>c.id===id?{...c,is_active:false}:c))}
 const cards=[{label:"Total Categories",value:stats.total,grad:"from-blue-500 to-indigo-600"},{label:"Active",value:stats.active,grad:"from-emerald-500 to-teal-600"},{label:"Items",value:stats.items,grad:"from-amber-500 to-orange-600"}];
 return <div className={`${embedded?"max-w-none":"mx-auto max-w-6xl px-4 py-8 lg:px-8"} catalog-premium`}><div className="catalog-header flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[0.18em] text-amber-600">Catalog</p><h1 className="text-2xl font-bold text-slate-900">Categories</h1><p className="text-sm text-slate-500">Organize products and services into clear groups.</p></div><button onClick={()=>setModal({mode:"create"})} className="catalog-primary-action rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700">+ Add Category</button></div>
 <div className="catalog-stats mt-6 grid grid-cols-2 gap-4 lg:grid-cols-3">{cards.map(c=><div key={c.label} className="catalog-stat relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className={`absolute inset-x-0 top-0 h-1 bg-gradient-to-r ${c.grad}`}/><p className="text-xs font-medium text-slate-500">{c.label}</p><p className="mt-1 text-xl font-bold text-slate-900">{c.value}</p></div>)}</div>
 <div className="catalog-toolbar mt-6 flex flex-wrap items-center gap-3"><div className="relative w-full max-w-xs"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search categories..." className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-9 pr-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"/></div><div className="catalog-status flex rounded-xl bg-slate-100 p-1 text-sm">{(["all","active","inactive"] as const).map(s=><button key={s} onClick={()=>setStatus(s)} className={`rounded-lg px-3 py-2 ${status===s?"bg-white font-medium text-slate-900 shadow-sm":"text-slate-500"}`}>{s[0].toUpperCase()+s.slice(1)}</button>)}</div><span className="text-sm text-slate-500">{filtered.length} categories</span></div>
 <div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(c=>{const count=counts[c.id]??0;return <div key={c.id} className={`rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:shadow-md ${!c.is_active?"opacity-60":""}`}><div className="flex items-start gap-3"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br ${gradient(c.name)} text-xs font-bold text-white shadow-sm`}>{c.name.slice(0,2).toUpperCase()}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold text-slate-900">{c.name}</p><p className="truncate text-xs text-slate-400">{c.description||"No description"}</p><span className="mt-2 inline-block rounded-md bg-slate-100 px-1.5 py-0.5 text-[10px] font-medium text-slate-500">{count} item{count===1?"":"s"}</span></div><span className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-semibold ${c.is_active?"bg-emerald-100 text-emerald-700":"bg-slate-200 text-slate-500"}`}>{c.is_active?"Active":"Inactive"}</span></div><div className="mt-4 flex gap-2 border-t border-slate-100 pt-3"><button onClick={()=>setModal({mode:"edit",category:c})} className="min-h-10 rounded-lg border border-slate-200 px-3 text-xs font-medium text-slate-600 hover:bg-slate-50">Edit</button>{c.is_active&&<button onClick={()=>deactivate(c.id)} disabled={busy===c.id} className="min-h-10 rounded-lg border border-rose-200 px-3 text-xs font-medium text-rose-600 hover:bg-rose-50 disabled:opacity-50">{busy===c.id?"...":"Deactivate"}</button>}</div></div>})}{filtered.length===0&&<div className="catalog-empty col-span-full rounded-2xl border border-dashed border-slate-200 py-14 text-center"><p className="font-semibold text-slate-800">No categories found</p><p className="mt-1 text-sm text-slate-500">Try a different search or add a new category.</p><button onClick={()=>setModal({mode:"create"})} className="mt-4 rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white">+ Add Category</button></div>}</div>
 {modal&&<CategoryFormModal state={modal} onClose={()=>setModal(null)} onSave={save}/>}</div>
}
