// OpenNext Cloudflare custom worker.
// The generated OpenNext worker owns normal HTTP/Next.js requests; this wrapper
// adds the scheduled handler needed by Cloudflare Cron Triggers.
// @ts-ignore .open-next/worker.js is generated by the OpenNext build.
import { default as handler } from "./.open-next/worker.js";
import { runBusinessMonitorScan } from "./lib/ai/business-monitor";
import { createAdminClient } from "./lib/supabase/admin";
import { processPendingIngestionEvents } from "./lib/ai/ingestion-processor";

export default {
  fetch: handler.fetch,

  async scheduled() {
    const result = await runBusinessMonitorScan();
    console.log(
      `[AI Monitor Cron] completed at ${result.scannedAt}; created ${result.created.length} event(s)`,
    );
    try {
      const summary = await processPendingIngestionEvents(createAdminClient());
      console.log(
        `[AI Ingestion Cron] processed ${summary.processed}; reconciled ${summary.reconciled}, review ${summary.needsReview}, failed ${summary.failed}, drafts ${summary.draftsCreated}`,
      );
    } catch (err) {
      console.log(`[AI Ingestion Cron] failed: ${err instanceof Error ? err.message : err}`);
    }
  },
};
