-- Production ACL baseline for edit_invoice overloads (PR #67 evidence).
-- DERIVED VERBATIM from local backup cafeerp-production-backup-2026-09-21.dump
-- via: pg_restore --schema-only, filtered to GRANT/REVOKE on edit_invoice*.
-- No secrets. Required by scripts/pr67_security_review.py STEP 0 to reproduce
-- the exact production privilege state before applying the migration.
REVOKE ALL ON FUNCTION public.edit_invoice(p_invoice_id uuid, p_customer_id uuid, p_invoice_date date, p_subtotal numeric, p_discount numeric, p_total numeric, p_payments jsonb, p_items jsonb, p_reason text, p_idempotency_key text) FROM PUBLIC;
GRANT ALL ON FUNCTION public.edit_invoice(p_invoice_id uuid, p_customer_id uuid, p_invoice_date date, p_subtotal numeric, p_discount numeric, p_total numeric, p_payments jsonb, p_items jsonb, p_reason text, p_idempotency_key text) TO authenticated;
GRANT ALL ON FUNCTION public.edit_invoice(p_invoice_id uuid, p_customer_id uuid, p_invoice_date date, p_subtotal numeric, p_discount numeric, p_total numeric, p_payments jsonb, p_items jsonb, p_reason text, p_idempotency_key text) TO service_role;
REVOKE ALL ON FUNCTION public.edit_invoice(p_invoice_id uuid, p_customer_id uuid, p_invoice_date date, p_subtotal numeric, p_discount numeric, p_total numeric, p_payments jsonb, p_items jsonb, p_reason text, p_place_of_supply text, p_supply_type text, p_customer_gstin text, p_b2b_or_b2c text, p_total_taxable_value numeric, p_total_cgst numeric, p_total_sgst numeric, p_total_igst numeric, p_is_reverse_charge boolean, p_advance_used numeric) FROM PUBLIC;
GRANT ALL ON FUNCTION public.edit_invoice(p_invoice_id uuid, p_customer_id uuid, p_invoice_date date, p_subtotal numeric, p_discount numeric, p_total numeric, p_payments jsonb, p_items jsonb, p_reason text, p_place_of_supply text, p_supply_type text, p_customer_gstin text, p_b2b_or_b2c text, p_total_taxable_value numeric, p_total_cgst numeric, p_total_sgst numeric, p_total_igst numeric, p_is_reverse_charge boolean, p_advance_used numeric) TO authenticated;
GRANT ALL ON FUNCTION public.edit_invoice(p_invoice_id uuid, p_customer_id uuid, p_invoice_date date, p_subtotal numeric, p_discount numeric, p_total numeric, p_payments jsonb, p_items jsonb, p_reason text, p_place_of_supply text, p_supply_type text, p_customer_gstin text, p_b2b_or_b2c text, p_total_taxable_value numeric, p_total_cgst numeric, p_total_sgst numeric, p_total_igst numeric, p_is_reverse_charge boolean, p_advance_used numeric) TO service_role;
REVOKE ALL ON FUNCTION public.edit_invoice(p_invoice_id uuid, p_customer_id uuid, p_invoice_date date, p_subtotal numeric, p_discount numeric, p_total numeric, p_payments jsonb, p_items jsonb, p_reason text, p_place_of_supply text, p_supply_type text, p_customer_gstin text, p_b2b_or_b2c text, p_total_taxable_value numeric, p_total_cgst numeric, p_total_sgst numeric, p_total_igst numeric, p_is_reverse_charge boolean, p_advance_used numeric, p_idempotency_key text) FROM PUBLIC;
GRANT ALL ON FUNCTION public.edit_invoice(p_invoice_id uuid, p_customer_id uuid, p_invoice_date date, p_subtotal numeric, p_discount numeric, p_total numeric, p_payments jsonb, p_items jsonb, p_reason text, p_place_of_supply text, p_supply_type text, p_customer_gstin text, p_b2b_or_b2c text, p_total_taxable_value numeric, p_total_cgst numeric, p_total_sgst numeric, p_total_igst numeric, p_is_reverse_charge boolean, p_advance_used numeric, p_idempotency_key text) TO authenticated;
GRANT ALL ON FUNCTION public.edit_invoice(p_invoice_id uuid, p_customer_id uuid, p_invoice_date date, p_subtotal numeric, p_discount numeric, p_total numeric, p_payments jsonb, p_items jsonb, p_reason text, p_place_of_supply text, p_supply_type text, p_customer_gstin text, p_b2b_or_b2c text, p_total_taxable_value numeric, p_total_cgst numeric, p_total_sgst numeric, p_total_igst numeric, p_is_reverse_charge boolean, p_advance_used numeric, p_idempotency_key text) TO service_role;
REVOKE ALL ON FUNCTION public.edit_invoice_internal(p_invoice_id uuid, p_customer_id uuid, p_invoice_date date, p_subtotal numeric, p_discount numeric, p_total numeric, p_payments jsonb, p_items jsonb, p_reason text) FROM PUBLIC;
GRANT ALL ON FUNCTION public.edit_invoice_internal(p_invoice_id uuid, p_customer_id uuid, p_invoice_date date, p_subtotal numeric, p_discount numeric, p_total numeric, p_payments jsonb, p_items jsonb, p_reason text) TO service_role;
