"use client";

import React,{createContext,useContext,useEffect,useState}from"react";
export type DisplayMode="light"|"dark"|"system";export type GradientPreset="aurora"|"ocean-luxe"|"royal"|"sunset-luxe"|"emerald-luxe"|"cosmic";export type MotionMode="on"|"off";export type AccentColor="blue"|"emerald"|"violet"|"amber"|"rose"|"cyan";export type DensityMode="comfortable"|"compact";export type FontScale="standard"|"large";export type DesignStyle="ambient-swiss"|"soft-fintech"|"color-block-luxury"|"bento-editorial"|"warm-paper"|"soft-glass"|"dark-anchor"|"muted-rainbow"|"quiet-luxury"|"premium-hybrid";export type Theme=DisplayMode;
export interface DesignStyleOption{id:DesignStyle;name:string;description:string;primary:string;secondary:string;accent:string}
export const DESIGN_STYLES:DesignStyleOption[]=[
{id:"ambient-swiss",name:"01 · Ambient Swiss",description:"Warm editorial canvas with precise colour hierarchy",primary:"#4f46e5",secondary:"#0f766e",accent:"#635bff"},
{id:"soft-fintech",name:"02 · Soft Fintech",description:"Clean finance language with muted green and lavender surfaces",primary:"#166534",secondary:"#7c3aed",accent:"#2563eb"},
{id:"color-block-luxury",name:"03 · Colour-Block Luxury",description:"Large restrained colour blocks with premium typography",primary:"#4338ca",secondary:"#c2410c",accent:"#0f766e"},
{id:"bento-editorial",name:"04 · Bento Editorial",description:"Asymmetric bento composition with stronger editorial hierarchy",primary:"#111827",secondary:"#7c3aed",accent:"#2563eb"},
{id:"warm-paper",name:"05 · Warm Paper",description:"Soft paper neutrals with rose, olive and ochre accents",primary:"#7c2d12",secondary:"#3f6212",accent:"#be123c"},
{id:"soft-glass",name:"06 · Soft Glass",description:"Solid surfaces with selective translucent floating controls",primary:"#155e75",secondary:"#7e22ce",accent:"#0891b2"},
{id:"dark-anchor",name:"07 · Dark Anchor",description:"Light-first canvas punctuated by rich dark analytics anchors",primary:"#1e1b4b",secondary:"#0f766e",accent:"#4f46e5"},
{id:"muted-rainbow",name:"08 · Muted Rainbow",description:"Grown-up plum, blue, sage, terracotta and ochre palette",primary:"#6b21a8",secondary:"#3f6212",accent:"#c2410c"},
{id:"quiet-luxury",name:"09 · Quiet Luxury",description:"Low chrome, sharp spacing and elegant monochrome hierarchy",primary:"#18181b",secondary:"#52525b",accent:"#2563eb"},
{id:"premium-hybrid",name:"10 · Premium Hybrid",description:"Ambient Swiss + muted rainbow + dark anchors + editorial bento",primary:"#4338ca",secondary:"#0f766e",accent:"#7c3aed"},
];
export interface AccentOption{key:AccentColor;label:string;colorHex:string;ringClass:string;badgeClass:string;primaryClass:string}
export const ACCENT_PALETTES:AccentOption[]=[
{key:"blue",label:"Ocean Sapphire",colorHex:"#2563eb",ringClass:"ring-blue-500/20",badgeClass:"bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300",primaryClass:"bg-blue-600 hover:bg-blue-700 text-white"},
{key:"emerald",label:"Emerald Mint",colorHex:"#059669",ringClass:"ring-emerald-500/20",badgeClass:"bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300",primaryClass:"bg-emerald-600 hover:bg-emerald-700 text-white"},
{key:"violet",label:"Royal Violet",colorHex:"#7c3aed",ringClass:"ring-violet-500/20",badgeClass:"bg-violet-100 text-violet-700 dark:bg-violet-950 dark:text-violet-300",primaryClass:"bg-violet-600 hover:bg-violet-700 text-white"},
{key:"amber",label:"Sunset Amber",colorHex:"#d97706",ringClass:"ring-amber-500/20",badgeClass:"bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300",primaryClass:"bg-amber-600 hover:bg-amber-700 text-white"},
{key:"rose",label:"Crimson Rose",colorHex:"#e11d48",ringClass:"ring-rose-500/20",badgeClass:"bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300",primaryClass:"bg-rose-600 hover:bg-rose-700 text-white"},
{key:"cyan",label:"Electric Cyan",colorHex:"#0891b2",ringClass:"ring-cyan-500/20",badgeClass:"bg-cyan-100 text-cyan-700 dark:bg-cyan-950 dark:text-cyan-300",primaryClass:"bg-cyan-600 hover:bg-cyan-700 text-white"},
];
export interface GradientPresetOption{id:GradientPreset;name:string;mood:string;primaryName:string;secondaryName:string;highlightName:string;primary:string;secondary:string;highlight:string;previewBg:string}
export const GRADIENT_PRESETS:GradientPresetOption[]=[
{id:"aurora",name:"Aurora",mood:"Sapphire Blue, Violet & Cyan",primaryName:"Sapphire Blue",secondaryName:"Violet",highlightName:"Cyan",primary:"#2563eb",secondary:"#7c3aed",highlight:"#06b6d4",previewBg:"from-blue-600/30 via-violet-600/30 to-cyan-500/30"},
{id:"ocean-luxe",name:"Ocean Luxe",mood:"Deep Blue, Teal & Cyan",primaryName:"Deep Blue",secondaryName:"Teal",highlightName:"Cyan",primary:"#1d4ed8",secondary:"#0d9488",highlight:"#06b6d4",previewBg:"from-blue-700/30 via-teal-600/30 to-cyan-500/30"},
{id:"royal",name:"Royal",mood:"Indigo, Violet & Soft Blue",primaryName:"Indigo",secondaryName:"Violet",highlightName:"Soft Blue",primary:"#4f46e5",secondary:"#9333ea",highlight:"#38bdf8",previewBg:"from-indigo-600/30 via-purple-600/30 to-sky-400/30"},
{id:"sunset-luxe",name:"Sunset Luxe",mood:"Amber, Rose & Violet",primaryName:"Amber",secondaryName:"Rose",highlightName:"Violet",primary:"#d97706",secondary:"#e11d48",highlight:"#8b5cf6",previewBg:"from-amber-500/30 via-rose-500/30 to-purple-600/30"},
{id:"emerald-luxe",name:"Emerald Luxe",mood:"Emerald, Teal & Cyan",primaryName:"Emerald",secondaryName:"Teal",highlightName:"Cyan",primary:"#059669",secondary:"#0d9488",highlight:"#06b6d4",previewBg:"from-emerald-600/30 via-teal-600/30 to-cyan-500/30"},
{id:"cosmic",name:"Cosmic",mood:"Deep Violet, Blue & Magenta",primaryName:"Deep Violet",secondaryName:"Blue",highlightName:"Magenta",primary:"#6d28d9",secondary:"#2563eb",highlight:"#d946ef",previewBg:"from-purple-700/30 via-blue-600/30 to-fuchsia-500/30"},
];
const KEYS={display:"sccomm-display-mode",gradient:"sccomm-gradient-enabled",preset:"sccomm-gradient-preset",motion:"sccomm-motion-enabled",accent:"sccomm-accent",density:"sccomm-density",font:"sccomm-font-scale",style:"cafe-erp-design-style",legacy:"sccomm-theme"};
interface ThemeContextValue{displayMode:DisplayMode;resolvedDisplayMode:"light"|"dark";gradientEnabled:boolean;gradientPreset:GradientPreset;motion:MotionMode;accent:AccentColor;density:DensityMode;fontScale:FontScale;designStyle:DesignStyle;setDisplayMode:(v:DisplayMode)=>void;setGradientEnabled:(v:boolean)=>void;setGradientPreset:(v:GradientPreset)=>void;setMotion:(v:MotionMode)=>void;setAccent:(v:AccentColor)=>void;setDensity:(v:DensityMode)=>void;setFontScale:(v:FontScale)=>void;setDesignStyle:(v:DesignStyle)=>void;toggleDisplayMode:()=>void;resetToDefaults:()=>void;theme:DisplayMode;resolvedTheme:"light"|"dark";designStyleLegacy:"modern-spatial";design:"modern-spatial";setTheme:(v:DisplayMode)=>void;toggleTheme:()=>void}
const ThemeContext=createContext<ThemeContextValue|null>(null);const STYLE_IDS=DESIGN_STYLES.map(s=>s.id) as readonly DesignStyle[];
function stored<T extends string>(key:string,fallback:T,values:readonly T[]){if(typeof window==="undefined")return fallback;const v=localStorage.getItem(key) as T|null;return v&&values.includes(v)?v:fallback}
export function getStoredDisplayMode(){return stored(KEYS.display,"light",["light","dark","system"])}
export function getStoredGradientEnabled(){return typeof window!=="undefined"&&localStorage.getItem(KEYS.gradient)==="true"}
export function getStoredGradientPreset(){return stored(KEYS.preset,"aurora",GRADIENT_PRESETS.map(p=>p.id))}
export function getStoredMotion(){return stored(KEYS.motion,"on",["on","off"])}
export function getStoredAccent(){return stored(KEYS.accent,"violet",ACCENT_PALETTES.map(p=>p.key))}
export function getStoredDensity(){return stored(KEYS.density,"comfortable",["comfortable","compact"])}
export function getStoredFontScale(){return stored(KEYS.font,"standard",["standard","large"])}
export function getStoredDesignStyle(){return stored(KEYS.style,"premium-hybrid",STYLE_IDS)}
export function applyTheme(m:DisplayMode,ge=false,gp:GradientPreset="aurora",mo:MotionMode="on",a:AccentColor="violet",d:DensityMode="comfortable",f:FontScale="standard",s:DesignStyle="premium-hybrid"){if(typeof document==="undefined")return;const r=document.documentElement,dark=m==="dark"||(m==="system"&&window.matchMedia("(prefers-color-scheme: dark)").matches);r.classList.toggle("dark",dark);r.setAttribute("data-display-mode",dark?"dark":"light");r.setAttribute("data-theme",dark?"dark":"light");r.setAttribute("data-design-style",s);r.setAttribute("data-gradient-enabled",String(ge));r.setAttribute("data-gradient-preset",gp);r.setAttribute("data-motion",mo);r.classList.toggle("motion-reduce",mo==="off");r.setAttribute("data-accent",a);r.setAttribute("data-density",d);r.setAttribute("data-font-scale",f);r.classList.toggle("density-compact",d==="compact");r.classList.toggle("font-scale-large",f==="large")}
export const getTheme=getStoredDisplayMode;export const setTheme=(m:DisplayMode)=>{try{localStorage.setItem(KEYS.display,m);localStorage.setItem(KEYS.legacy,m)}catch{}applyTheme(m,getStoredGradientEnabled(),getStoredGradientPreset(),getStoredMotion(),getStoredAccent(),getStoredDensity(),getStoredFontScale(),getStoredDesignStyle())};
export default function ThemeProvider({children}:{children:React.ReactNode}){const[displayMode,setDisplay]=useState<DisplayMode>("light"),[gradientEnabled,setGradient]=useState(false),[gradientPreset,setPreset]=useState<GradientPreset>("aurora"),[motion,setMotionState]=useState<MotionMode>("on"),[accent,setAccentState]=useState<AccentColor>("violet"),[density,setDensityState]=useState<DensityMode>("comfortable"),[fontScale,setFontScaleState]=useState<FontScale>("standard"),[designStyle,setStyle]=useState<DesignStyle>("premium-hybrid"),[resolvedDisplayMode,setResolved]=useState<"light"|"dark">("light");
useEffect(()=>{const m=getStoredDisplayMode(),g=getStoredGradientEnabled(),p=getStoredGradientPreset(),mo=getStoredMotion(),a=getStoredAccent(),d=getStoredDensity(),f=getStoredFontScale(),s=getStoredDesignStyle();setDisplay(m);setGradient(g);setPreset(p);setMotionState(mo);setAccentState(a);setDensityState(d);setFontScaleState(f);setStyle(s);const sync=()=>setResolved(m==="dark"||(m==="system"&&matchMedia("(prefers-color-scheme: dark)").matches)?"dark":"light");sync();applyTheme(m,g,p,mo,a,d,f,s);const mq=matchMedia("(prefers-color-scheme: dark)"),fn=()=>{if(getStoredDisplayMode()==="system"){setResolved(mq.matches?"dark":"light");applyTheme("system",getStoredGradientEnabled(),getStoredGradientPreset(),getStoredMotion(),getStoredAccent(),getStoredDensity(),getStoredFontScale(),getStoredDesignStyle())}};mq.addEventListener("change",fn);return()=>mq.removeEventListener("change",fn)},[]);
function update(partial:Partial<{displayMode:DisplayMode;gradientEnabled:boolean;gradientPreset:GradientPreset;motion:MotionMode;accent:AccentColor;density:DensityMode;fontScale:FontScale;designStyle:DesignStyle}>){const n={displayMode,gradientEnabled,gradientPreset,motion,accent,density,fontScale,designStyle,...partial};if(partial.displayMode)setDisplay(partial.displayMode);if(partial.gradientEnabled!==undefined)setGradient(partial.gradientEnabled);if(partial.gradientPreset)setPreset(partial.gradientPreset);if(partial.motion)setMotionState(partial.motion);if(partial.accent)setAccentState(partial.accent);if(partial.density)setDensityState(partial.density);if(partial.fontScale)setFontScaleState(partial.fontScale);if(partial.designStyle)setStyle(partial.designStyle);try{const map:Record<string,string>={displayMode:KEYS.display,gradientEnabled:KEYS.gradient,gradientPreset:KEYS.preset,motion:KEYS.motion,accent:KEYS.accent,density:KEYS.density,fontScale:KEYS.font,designStyle:KEYS.style};Object.entries(partial).forEach(([k,v])=>localStorage.setItem(map[k],String(v)));if(partial.displayMode)localStorage.setItem(KEYS.legacy,partial.displayMode)}catch{}const dark=n.displayMode==="dark"||(n.displayMode==="system"&&matchMedia("(prefers-color-scheme: dark)").matches);setResolved(dark?"dark":"light");applyTheme(n.displayMode,n.gradientEnabled,n.gradientPreset,n.motion,n.accent,n.density,n.fontScale,n.designStyle)}
const resetToDefaults=()=>update({displayMode:"light",gradientEnabled:false,gradientPreset:"aurora",motion:"on",accent:"violet",density:"comfortable",fontScale:"standard",designStyle:"premium-hybrid"});const toggleDisplayMode=()=>update({displayMode:resolvedDisplayMode==="dark"?"light":"dark"});
return <ThemeContext.Provider value={{displayMode,resolvedDisplayMode,gradientEnabled,gradientPreset,motion,accent,density,fontScale,designStyle,setDisplayMode:v=>update({displayMode:v}),setGradientEnabled:v=>update({gradientEnabled:v}),setGradientPreset:v=>update({gradientPreset:v}),setMotion:v=>update({motion:v}),setAccent:v=>update({accent:v}),setDensity:v=>update({density:v}),setFontScale:v=>update({fontScale:v}),setDesignStyle:v=>update({designStyle:v}),toggleDisplayMode,resetToDefaults,theme:displayMode,resolvedTheme:resolvedDisplayMode,designStyleLegacy:"modern-spatial",design:"modern-spatial",setTheme:v=>update({displayMode:v}),toggleTheme:toggleDisplayMode}}>{children}</ThemeContext.Provider>}
export function useTheme(){const ctx=useContext(ThemeContext);if(!ctx)throw new Error("useTheme must be used within a ThemeProvider");return ctx}
