#include <windows.h>
#include <objbase.h>
#include <mfapi.h>
#include <mfidl.h>
#include <mfvirtualcamera.h>
#include <ks.h>
#include <ksmedia.h>
#include <wil/com.h>
#include <wil/result.h>
#include <iostream>
#include <string>
#include <vector>
#include <cwchar>
#include "../include/CafeCamShared.h"
#include "../CafeCamMediaSource/VirtualCameraMediaSource.h"
struct CameraInfo{std::wstring name;std::wstring link;};
std::wstring esc(const std::wstring&s){std::wstring o;for(wchar_t c:s){if(c==L'\\')o+=L"\\\\";else if(c==L'"')o+=L"\\\"";else if(c==L'\n')o+=L"\\n";else if(c==L'\r')o+=L"\\r";else o+=c;}return o;}
void err(HRESULT h,const wchar_t*op){wchar_t b[32]{};swprintf_s(b,L"0x%08X",(unsigned)h);std::wcout<<L"{\"ok\":false,\"operation\":\""<<esc(op)<<L"\",\"hr\":\""<<b<<L"\"}"<<std::endl;}
HRESULT enumerate(std::vector<CameraInfo>&out){out.clear();wil::com_ptr_nothrow<IMFAttributes>a;RETURN_IF_FAILED(MFCreateAttributes(&a,2));RETURN_IF_FAILED(a->SetGUID(MF_DEVSOURCE_ATTRIBUTE_SOURCE_TYPE,MF_DEVSOURCE_ATTRIBUTE_SOURCE_TYPE_VIDCAP_GUID));RETURN_IF_FAILED(a->SetGUID(MF_DEVSOURCE_ATTRIBUTE_SOURCE_TYPE_VIDCAP_CATEGORY,KSCATEGORY_VIDEO_CAMERA));wil::unique_cotaskmem_array_ptr<wil::com_ptr_nothrow<IMFActivate>>acts;UINT32 n=0;RETURN_IF_FAILED(MFEnumDeviceSources(a.get(),acts.addressof(),&n));for(UINT32 i=0;i<n;i++){wil::unique_cotaskmem_string name,link;UINT32 c=0;if(FAILED(acts[i]->GetAllocatedString(MF_DEVSOURCE_ATTRIBUTE_FRIENDLY_NAME,&name,&c)))continue;c=0;if(FAILED(acts[i]->GetAllocatedString(MF_DEVSOURCE_ATTRIBUTE_SOURCE_TYPE_VIDCAP_SYMBOLIC_LINK,&link,&c)))continue;out.push_back({name.get(),link.get()});}return S_OK;}
bool cafe(const CameraInfo&c){return _wcsicmp(c.name.c_str(),kCafeCamFriendlyName)==0||_wcsnicmp(c.name.c_str(),L"CafeCAM",7)==0;}
HRESULT install(CafeCamKind kind,const wchar_t*wrapped){wil::com_ptr_nothrow<IMFVirtualCamera>vc;RETURN_IF_FAILED(MFCreateVirtualCamera(MFVirtualCameraType_SoftwareCameraSource,MFVirtualCameraLifetime_System,MFVirtualCameraAccess_CurrentUser,kCafeCamFriendlyName,kCafeCamSourceId,nullptr,0,&vc));RETURN_HR_IF_NULL(E_FAIL,vc.get());RETURN_IF_FAILED(vc->SetUINT32(VCAM_KIND,(UINT32)kind));if(wrapped&&*wrapped){RETURN_IF_FAILED(vc->AddDeviceSourceInfo(wrapped));RETURN_IF_FAILED(vc->SetString(VCAM_DEVICE_INFO,wrapped));}RETURN_IF_FAILED(vc->Start(nullptr));wil::unique_cotaskmem_string link;UINT32 c=0;RETURN_IF_FAILED(vc->GetAllocatedString(MF_DEVSOURCE_ATTRIBUTE_SOURCE_TYPE_VIDCAP_SYMBOLIC_LINK,&link,&c));std::wcout<<L"{\"ok\":true,\"name\":\"CafeCAM\",\"symbolicLink\":\""<<esc(link.get()?link.get():L"")<<L"\",\"kind\":"<<(UINT32)kind<<L"}"<<std::endl;return S_OK;}
HRESULT removeCafe(){std::vector<CameraInfo> cams;RETURN_IF_FAILED(enumerate(cams));for(const auto&c:cams){if(!cafe(c))continue;wil::com_ptr_nothrow<IMFVirtualCamera>vc;HRESULT h=MFCreateVirtualCamera(MFVirtualCameraType_SoftwareCameraSource,MFVirtualCameraLifetime_System,MFVirtualCameraAccess_CurrentUser,kCafeCamFriendlyName,kCafeCamSourceId,nullptr,0,&vc);if(SUCCEEDED(h))h=vc->Remove();if(SUCCEEDED(h)){vc->Shutdown();std::wcout<<L"{\"ok\":true,\"removed\":true}"<<std::endl;return S_OK;}}std::wcout<<L"{\"ok\":true,\"removed\":false,\"reason\":\"not-installed\"}"<<std::endl;return S_OK;}
HRESULT status(){std::vector<CameraInfo>cams;RETURN_IF_FAILED(enumerate(cams));std::wcout<<L"{\"supported\":true,\"installed\":[";bool f=true;for(const auto&c:cams){if(!cafe(c))continue;if(!f)std::wcout<<L",";f=false;std::wcout<<L"{\"name\":\""<<esc(c.name)<<L"\",\"symbolicLink\":\""<<esc(c.link)<<L"\"}";}std::wcout<<L"]}"<<std::endl;return S_OK;}
HRESULT list(){std::vector<CameraInfo>cams;RETURN_IF_FAILED(enumerate(cams));std::wcout<<L"[";for(size_t i=0;i<cams.size();i++){if(i)std::wcout<<L",";std::wcout<<L"{\"name\":\""<<esc(cams[i].name)<<L"\",\"symbolicLink\":\""<<esc(cams[i].link)<<L"\"}";}std::wcout<<L"]"<<std::endl;return S_OK;}
HRESULT selftest(){BOOL supported=FALSE;RETURN_IF_FAILED(MFIsVirtualCameraTypeSupported(MFVirtualCameraType_SoftwareCameraSource,&supported));std::wcout<<L"{\"ok\":"<<(supported?L"true":L"false")<<L",\"supported\":"<<(supported?L"true":L"false")<<L"}"<<std::endl;return S_OK;}
int wmain(int argc,wchar_t*argv[]){HRESULT ci=CoInitializeEx(nullptr,COINIT_MULTITHREADED);if(FAILED(ci)&&ci!=RPC_E_CHANGED_MODE){err(ci,L"CoInitializeEx");return 1;}HRESULT h=MFStartup(MF_VERSION);if(FAILED(h)){err(h,L"MFStartup");if(ci!=RPC_E_CHANGED_MODE)CoUninitialize();return 1;}HRESULT op=E_INVALIDARG;if(argc>=2&&!_wcsicmp(argv[1],L"self-test"))op=selftest();else if(argc>=2&&!_wcsicmp(argv[1],L"status"))op=status();else if(argc>=2&&!_wcsicmp(argv[1],L"list-cameras"))op=list();else if(argc>=2&&!_wcsicmp(argv[1],L"install-synthetic"))op=install(CafeCamKind::Synthetic,nullptr);else if(argc>=3&&!_wcsicmp(argv[1],L"install-wrapper"))op=install(CafeCamKind::PhysicalWrapper,argv[2]);else if(argc>=2&&!_wcsicmp(argv[1],L"remove"))op=removeCafe();else err(E_INVALIDARG,L"usage");if(FAILED(op))err(op,L"operation");MFShutdown();if(ci!=RPC_E_CHANGED_MODE)CoUninitialize();return SUCCEEDED(op)?0:1;}