"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
type Camera={name:string;symbolicLink:string};
const native=()=> (window as any).electronAPI;
export default function CafeCamPage(){
 const [electron,setElectron]=useState(false),[installed,setInstalled]=useState<Camera[]>([]),[cameras,setCameras]=useState<Camera[]>([]),[selected,setSelected]=useState(""),[busy,setBusy]=useState(""),[message,setMessage]=useState("Checking CafeCAM…");
 const refresh=useCallback(async()=>{const api=native();if(!api?.isElectron){setMessage("CafeCAM controls are available in the Windows CafeERP desktop app.");return;}setElectron(true);setBusy("refresh");try{const [s,l]=await Promise.all([api.getCafeCamStatus(),api.listCafeCamCameras()]);if(s?.success)setInstalled(s.data?.installed||[]);if(l?.success&&Array.isArray(l.data)){setCameras(l.data);setSelected((v:string)=>v||l.data[0]?.symbolicLink||"");}setMessage(s?.success?"CafeCAM status refreshed.":(s?.error||"CafeCAM manager unavailable."));}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy("");}},[]);
 useEffect(()=>{void refresh();},[refresh]);
 const physical=useMemo(()=>cameras.filter(c=>!/^cafecam\b/i.test(c.name)),[cameras]);
 async function action(kind:string){const api=native();if(!api?.isElectron)return;setBusy(kind);try{let r:any;if(kind==="test")r=await api.cafeCamSelfTest();if(kind==="install")r=await api.installCafeCamSynthetic();if(kind==="remove")r=await api.removeCafeCam();if(kind==="wrap"){if(!selected)throw new Error("Select a physical camera first.");r=await api.installCafeCamWrapper(selected);}setMessage(r?.success?"CafeCAM operation completed.":(r?.error||"CafeCAM operation failed."));await refresh();}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy("");}}
 return <div className="mx-auto w-full max-w-6xl"><section className="rounded-3xl border border-slate-200/80 bg-white/80 p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900/80">
  <div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div><div className="mb-2 inline-flex rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1 text-[11px] font-bold text-indigo-700 dark:border-indigo-500/30 dark:bg-indigo-950/40 dark:text-indigo-300">Native Camera Control</div><h1 className="text-2xl font-black text-slate-900 dark:text-white">CafeCAM</h1><p className="mt-1 text-sm leading-6 text-slate-500 dark:text-slate-400">Register a Windows virtual camera or wrap a physical webcam for camera-aware applications.</p></div>
  <div className={installed.length?"rounded-2xl border border-emerald-300 bg-emerald-50 px-4 py-3 text-right dark:border-emerald-500/30 dark:bg-emerald-950/30":"rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-right dark:border-slate-700 dark:bg-slate-800"}><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">Status</div><div className="mt-1 text-lg font-black">{installed.length?"Installed":"Not installed"}</div></div></div>
  {!electron&&<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800 dark:border-amber-500/30 dark:bg-amber-950/30">{message}</div>}
  <div className="mt-6 grid gap-4 md:grid-cols-3">
   <button onClick={()=>action("test")} disabled={!electron||!!busy} className="rounded-2xl border p-4 text-left shadow-sm disabled:opacity-50"><b>Self-test</b><div className="mt-1 text-xs opacity-70">Check Windows virtual-camera support.</div></button>
   <button onClick={()=>action("install")} disabled={!electron||!!busy} className="rounded-2xl border border-indigo-200 bg-indigo-50 p-4 text-left shadow-sm disabled:opacity-50 dark:border-indigo-500/30 dark:bg-indigo-950/30"><b>Install CafeCAM</b><div className="mt-1 text-xs opacity-70">Register the synthetic virtual camera.</div></button>
   <button onClick={()=>action("remove")} disabled={!electron||!!busy} className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-left shadow-sm disabled:opacity-50 dark:border-rose-500/30 dark:bg-rose-950/30"><b>Remove CafeCAM</b><div className="mt-1 text-xs opacity-70">Unregister the CafeCAM device.</div></button>
  </div>
  <div className="mt-6 rounded-2xl border p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-sm font-black">Physical camera wrapper</h2><p className="text-xs text-slate-500 dark:text-slate-400">Expose an existing webcam through CafeCAM.</p></div><button onClick={()=>action("wrap")} disabled={!electron||!!busy||!selected} className="rounded-xl bg-slate-900 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50 dark:bg-white dark:text-slate-900">Wrap selected camera</button></div>
  <select value={selected} onChange={e=>setSelected(e.target.value)} disabled={!electron||!!busy} className="mt-4 w-full rounded-xl border bg-white px-3 py-2.5 text-sm dark:bg-slate-900"><option value="">Select a camera…</option>{physical.map(c=><option key={c.symbolicLink} value={c.symbolicLink}>{c.name}</option>)}</select></div>
  <div className="mt-5 rounded-xl border px-4 py-3 text-xs text-slate-600 dark:text-slate-300">{busy?"Working: "+busy+"…":message}</div>
 </section></div>;
}