"use client";

import { useEffect, useState } from "react";
import { DEFAULT_AUTOMATIONS, DEFAULT_WA_CONFIG, type WhatsAppAutomationRules, type WhatsAppProvider } from "@/lib/whatsapp";

type ConfigResponse = { provider: WhatsAppProvider; gateway_url?: string; meta_waba_id?: string; meta_display_phone_number?: string; meta_phone_number_id?: string; meta_access_token_set?: boolean; meta_app_secret_set?: boolean; verify_token_set?: boolean; automations: WhatsAppAutomationRules; ai_customer_reply?: { enabled: boolean; language: string; tone: string; instructions: string }; configured: boolean };
const DEFAULT_WABA_ID = "448036473626878";
const DEFAULT_DISPLAY_PHONE = "+91 70030 37208";
const META_CLOUD_GUIDE = "https://developers.facebook.com/docs/whatsapp/cloud-api";
const META_EMBEDDED_SIGNUP_GUIDE = "https://developers.facebook.com/docs/whatsapp/embedded-signup";

export default function WhatsAppConfigurationPanel() {
  const [cfg, setCfg] = useState<ConfigResponse>({ provider: "off", gateway_url: DEFAULT_WA_CONFIG.gateway_url, automations: DEFAULT_AUTOMATIONS, ai_customer_reply: { enabled: false, language: "auto", tone: "friendly_direct", instructions: "" }, configured: false });
  const [token, setToken] = useState(""); const [appSecret, setAppSecret] = useState(""); const [verifyToken, setVerifyToken] = useState("");
  const [phoneId, setPhoneId] = useState(""); const [wabaId, setWabaId] = useState(DEFAULT_WABA_ID); const [displayPhone, setDisplayPhone] = useState(DEFAULT_DISPLAY_PHONE); const [gatewayUrl, setGatewayUrl] = useState(DEFAULT_WA_CONFIG.gateway_url || ""); const [provider, setProvider] = useState<WhatsAppProvider>("off");
  const [saving, setSaving] = useState(false); const [resolving, setResolving] = useState(false); const [testing, setTesting] = useState(false);
  const [message, setMessage] = useState<{ ok: boolean; text: string } | null>(null); const [testPhone, setTestPhone] = useState("");
  const [senderPlatform, setSenderPlatform] = useState(""); const [codeVerificationStatus, setCodeVerificationStatus] = useState("");

  async function load() { const res = await fetch("/api/whatsapp/config", { cache: "no-store" }); if (!res.ok) return; const data = (await res.json()) as ConfigResponse; setCfg(data); setProvider(data.provider || "off"); setGatewayUrl(data.gateway_url || ""); setWabaId(data.meta_waba_id || DEFAULT_WABA_ID); setDisplayPhone(data.meta_display_phone_number || DEFAULT_DISPLAY_PHONE); setPhoneId(data.meta_phone_number_id || ""); }
  useEffect(() => { void load(); }, []);

  async function save() { setSaving(true); setMessage(null); try { const res = await fetch("/api/whatsapp/config", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider, gateway_url: gatewayUrl, meta_waba_id: wabaId, meta_display_phone_number: displayPhone, meta_phone_number_id: phoneId, meta_access_token: token || undefined, meta_app_secret: appSecret || undefined, verify_token: verifyToken || undefined, automations: cfg.automations, ai_customer_reply: cfg.ai_customer_reply }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Could not save configuration"); setToken(""); setAppSecret(""); setVerifyToken(""); setMessage({ ok: true, text: "WhatsApp configuration saved securely." }); await load(); } catch (err: any) { setMessage({ ok: false, text: err?.message || "Could not save configuration" }); } finally { setSaving(false); } }

  async function resolveSender() { setResolving(true); setMessage(null); try { const res = await fetch("/api/whatsapp/config/resolve", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ waba_id: wabaId, display_phone_number: displayPhone }) }); const data = await res.json(); if (!res.ok || !data.success) throw new Error(data.error || "Could not resolve Meta Phone Number ID"); setPhoneId(data.phone_number_id || ""); setWabaId(data.waba_id || wabaId); setDisplayPhone(data.display_phone_number || displayPhone); setSenderPlatform(data.platform_type || ""); setCodeVerificationStatus(data.code_verification_status || ""); setMessage({ ok: true, text: data.coexistence_required ? "Meta found this number as a WhatsApp Business App (ON_PREMISE) sender. It must be connected to Cloud API through Meta Embedded Signup / Coexistence; the direct Register Sender API is not supported for this SMB number." : `Meta sender verified: ${data.display_phone_number || displayPhone} → ${data.phone_number_id}` }); await load(); } catch (err: any) { setMessage({ ok: false, text: err?.message || "Could not resolve Meta Phone Number ID" }); } finally { setResolving(false); } }

  async function testConnection() { setTesting(true); setMessage(null); try { const senderDigits = displayPhone.replace(/\D/g, ""); const recipientDigits = testPhone.replace(/\D/g, ""); if (senderDigits && recipientDigits === senderDigits) throw new Error("Use a different WhatsApp number as the recipient. The business sender cannot be its own test recipient."); const res = await fetch("/api/whatsapp/config/test", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ phone: testPhone }) }); const data = await res.json(); if (!res.ok || !data.success) throw new Error(data.error || "Test message failed"); setMessage({ ok: true, text: `Test message accepted by ${data.provider || "WhatsApp"}. Sender ID: ${data.resolvedPhoneNumberId || "verified"}` }); await load(); } catch (err: any) { setMessage({ ok: false, text: err?.message || "Test message failed" }); } finally { setTesting(false); } }
  function toggle(key: keyof WhatsAppAutomationRules) { setCfg((old) => ({ ...old, automations: { ...old.automations, [key]: !old.automations[key] } })); }

  return <div className="space-y-6">
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-slate-900">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-600">Official Cloud API</p><h2 className="mt-1 text-xl font-black text-slate-900 dark:text-white">Connect WhatsApp</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500 dark:text-slate-400">Credentials are stored server-side. The browser never receives the access token, app secret, or webhook secret.</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${cfg.configured ? "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300" : "bg-amber-50 text-amber-700 dark:bg-amber-950/30 dark:text-amber-300"}`}>{cfg.configured ? "Configured" : "Not configured"}</span></div>
      <div className="mt-6 grid gap-4 md:grid-cols-2">
        <Field label="Provider"><select value={provider} onChange={(e) => setProvider(e.target.value as WhatsAppProvider)} className={inputClass}><option value="off">Disabled</option><option value="meta">Meta WhatsApp Cloud API</option><option value="local_gateway">Local Gateway (legacy)</option><option value="ultramsg">UltraMsg (legacy)</option></select></Field>
        {provider === "meta" && <><Field label="WhatsApp Business Account (WABA) ID"><input value={wabaId} onChange={(e) => setWabaId(e.target.value)} placeholder="WABA ID" className={inputClass} /></Field><Field label="Business WhatsApp Number"><input value={displayPhone} onChange={(e) => setDisplayPhone(e.target.value)} placeholder="+91..." className={inputClass} /></Field><Field label="Cloud API Phone Number ID"><input value={phoneId} onChange={(e) => setPhoneId(e.target.value)} placeholder="Click Resolve Sender ID" className={inputClass} /><p className="mt-1 text-[11px] text-slate-500">Do not use the WhatsApp Manager phone-profile ID here. Cafe-EPR resolves the Cloud API sender ID from the WABA.</p></Field></>}
        <Field label="Permanent Access Token"><input type="password" value={token} onChange={(e) => setToken(e.target.value)} placeholder={cfg.meta_access_token_set ? "Saved — enter only to replace" : "Paste Meta access token"} autoComplete="new-password" className={inputClass} /></Field><Field label="Meta App Secret"><input type="password" value={appSecret} onChange={(e) => setAppSecret(e.target.value)} placeholder={cfg.meta_app_secret_set ? "Saved — enter only to replace" : "Paste Meta app secret"} autoComplete="new-password" className={inputClass} /></Field><Field label="Webhook Verify Token"><input type="password" value={verifyToken} onChange={(e) => setVerifyToken(e.target.value)} placeholder={cfg.verify_token_set ? "Saved — enter only to replace" : "Create a strong verification token"} autoComplete="new-password" className={inputClass} /></Field><Field label="Gateway URL (legacy only)"><input value={gatewayUrl} onChange={(e) => setGatewayUrl(e.target.value)} placeholder="https://..." className={inputClass} disabled={provider === "meta" || provider === "off"} /></Field>
      </div>
      {provider === "meta" && <div className="mt-5 rounded-2xl border border-indigo-200 bg-indigo-50/70 p-4 dark:border-indigo-900/40 dark:bg-indigo-950/20"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-xs font-black text-indigo-900 dark:text-indigo-200">Resolve Meta sender status</div><div className="mt-1 text-xs text-indigo-800 dark:text-indigo-300">Cafe-EPR checks the WABA phone record and detects whether this number is already on the WhatsApp Business App.</div>{senderPlatform && <div className="mt-2 text-[11px] font-semibold text-indigo-700 dark:text-indigo-300">Platform: {senderPlatform}{codeVerificationStatus ? ` · Verification: ${codeVerificationStatus}` : ""}</div>}</div><button onClick={resolveSender} disabled={resolving || !wabaId.trim()} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{resolving ? "Checking..." : "Check Sender"}</button></div></div>}
      {provider === "meta" && <div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50/70 p-4 dark:border-amber-900/40 dark:bg-amber-950/20"><div className="text-xs font-black text-amber-900 dark:text-amber-200">WhatsApp Business App → Cloud API</div><div className="mt-1 text-xs leading-5 text-amber-800 dark:text-amber-300"><b>This number is an SMB / WhatsApp Business App sender.</b> Meta does not allow Cafe-EPR to register it with the direct <code>/register</code> endpoint. If you want to keep using WhatsApp Business on the phone, use Meta's <b>Embedded Signup / Coexistence</b> onboarding instead. Meta's coexistence flow connects the existing Business App number to Cloud API without asking Cafe-EPR to handle your WhatsApp PIN.</div><div className="mt-3 flex flex-wrap gap-2"><a href={META_EMBEDDED_SIGNUP_GUIDE} target="_blank" rel="noreferrer" className="rounded-xl bg-amber-600 px-4 py-2.5 text-xs font-bold text-white">Open Meta Embedded Signup Guide</a><a href={META_CLOUD_GUIDE} target="_blank" rel="noreferrer" className="rounded-xl border border-amber-300 px-4 py-2.5 text-xs font-bold text-amber-900 dark:border-amber-800 dark:text-amber-200">Cloud API Guide</a></div><p className="mt-3 text-[11px] leading-5 text-amber-800 dark:text-amber-300">Typical coexistence eligibility includes active use of the WhatsApp Business App and completing Meta's embedded onboarding/QR confirmation. Do not delete the WhatsApp Business account just to bypass this screen.</p></div>}
      <div className="mt-5 grid gap-3 lg:grid-cols-2"><div className="rounded-2xl border border-blue-200 bg-blue-50/70 p-4 text-xs leading-5 text-blue-900 dark:border-blue-900/40 dark:bg-blue-950/20 dark:text-blue-200">For Meta Cloud API, use a system-user token, the Cloud API Phone Number ID, an approved WhatsApp Business sender, the Meta App Secret, and a webhook verify token.</div><div className="rounded-2xl border border-emerald-200 bg-emerald-50/70 p-4 text-xs leading-5 text-emerald-900 dark:border-emerald-900/40 dark:bg-emerald-950/20 dark:text-emerald-200"><div className="font-black">Meta webhook callback URL</div><div className="mt-1 break-all font-mono text-[11px]">https://cafeerp.vercel.app/api/whatsapp/webhook</div><div className="mt-1">Subscribe your WhatsApp Business Account to the webhook after saving the secrets.</div></div></div>
      <div className="mt-5 flex flex-wrap gap-3"><button onClick={save} disabled={saving} className="rounded-xl bg-indigo-600 px-5 py-2.5 text-xs font-bold text-white disabled:opacity-50">{saving ? "Saving..." : "Save Securely"}</button><a href={META_CLOUD_GUIDE} target="_blank" rel="noreferrer" className="rounded-xl border border-slate-200 px-5 py-2.5 text-xs font-bold text-slate-700 dark:border-white/10 dark:text-slate-200">Meta Cloud API Guide</a></div>
    </section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-slate-900"><h2 className="text-lg font-black text-slate-900 dark:text-white">Connection Test</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Use a different WhatsApp number as the recipient. The business sender cannot be its own test recipient.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input value={testPhone} onChange={(e) => setTestPhone(e.target.value)} placeholder="10-digit recipient mobile" className={`${inputClass} sm:max-w-sm`} /><button onClick={testConnection} disabled={testing || !testPhone.trim()} className="rounded-xl bg-slate-900 px-5 py-2.5 text-xs font-bold text-white disabled:opacity-50 dark:bg-indigo-600">{testing ? "Testing..." : "Send Test Message"}</button></div>{message && <div className={`mt-4 rounded-xl p-3 text-xs font-semibold ${message.ok ? "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300" : "bg-rose-50 text-rose-700 dark:bg-rose-950/30 dark:text-rose-300"}`}>{message.text}</div>}</section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-slate-900"><h2 className="text-lg font-black text-slate-900 dark:text-white">Automatic Messages</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Choose which completed ERP events enqueue WhatsApp messages.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(cfg.automations).map(([key, enabled]) => <button key={key} onClick={() => toggle(key as keyof WhatsAppAutomationRules)} className="flex items-center justify-between rounded-2xl border border-slate-200 p-4 text-left dark:border-white/10"><span className="text-xs font-bold text-slate-700 dark:text-slate-200">{labelize(key)}</span><span className={`h-6 w-11 rounded-full p-1 ${enabled ? "bg-emerald-500" : "bg-slate-300 dark:bg-slate-700"}`}><span className={`block h-4 w-4 rounded-full bg-white transition ${enabled ? "translate-x-5" : "translate-x-0"}`} /></span></button>)}</div><button onClick={save} disabled={saving} className="mt-5 rounded-xl border border-slate-200 px-5 py-2.5 text-xs font-bold text-slate-700 dark:border-white/10 dark:text-slate-200">Save Automation Settings</button></section>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 block text-xs font-bold text-slate-600 dark:text-slate-300">{label}</span>{children}</label>; }
const inputClass = "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-indigo-500 dark:border-white/10 dark:bg-slate-800 dark:text-white";
function labelize(key: string) { return key.replace(/^auto_send_/, "").split("_").map((x) => x.charAt(0).toUpperCase() + x.slice(1)).join(" "); }