create or replace function public.run_canonical_self_audit(p_triggered_by text default 'manual') returns jsonb language plpgsql security definer set search_path=public as $function$
declare
  v_pool jsonb; v_bank_seed numeric; v_bank_seed_date date; v_bank_life numeric; v_bank_anchor numeric; v_bank_seed_exists boolean; v_pnl jsonb;
  v_neg int; v_trigger int; v_unbalanced int; v_orphan_invoice int; v_orphan_cash int; v_customer_mismatch int; v_secdef int; v_catalog_write int; v_cash_mutation int; v_rls_gap int;
  v_run uuid:=gen_random_uuid(); v_start timestamptz:=clock_timestamp(); v_pass int:=0; v_fail int:=0; v_warn int:=0; v_crit int:=0; v_findings jsonb; v_expected numeric; v_actual numeric; chk record;
begin
  if auth.uid() is null and auth.role()<>'service_role' and current_user<>'postgres' then raise exception 'Not authenticated'; end if;
  if auth.role()<>'service_role' and current_user<>'postgres' and not public.is_back_office() then raise exception 'Forbidden'; end if;
  v_pool:=public.get_pool_balances(current_date); v_bank_anchor:=coalesce((v_pool->'bank'->>'current')::numeric,0);
  select s.opening,s.seed_date into v_bank_seed,v_bank_seed_date from public.get_pool_seed('bank',current_date) s;
  v_bank_seed:=coalesce(v_bank_seed,0); v_bank_seed_exists:=coalesce(v_bank_seed_date,'0001-01-01'::date)<>'0001-01-01'::date; v_bank_seed_date:=coalesce(v_bank_seed_date,current_date); v_bank_life:=v_bank_seed+public.get_pool_movements('bank',v_bank_seed_date,current_date); v_pnl:=public.get_pnl(current_date,current_date);
  select count(*) into v_neg from public.products where stock_qty<0;
  select count(*) into v_trigger from information_schema.triggers where event_object_schema='public' and trigger_name in ('trg_prevent_posted_invoice_tax_mutation','trg_prevent_posted_invoice_item_tax_mutation');
  select count(*) into v_unbalanced from public.journal_entries j where j.status='posted' and abs((select coalesce(sum(l.debit-l.credit),0) from public.journal_lines l where l.journal_entry_id=j.id))>.01;
  with eff as (select j.id,coalesce(s.effective_source_type,j.source_type) effective_type,coalesce(s.effective_source_id,j.source_id) effective_id from public.journal_entries j left join public.journal_effective_sources s on s.journal_entry_id=j.id where j.status='posted') select count(*) into v_orphan_invoice from eff e where e.effective_type='invoice' and not exists(select 1 from public.invoices i where i.id=e.effective_id);
  with eff as (select j.id,coalesce(s.effective_source_type,j.source_type) effective_type,coalesce(s.effective_source_id,j.source_id) effective_id from public.journal_entries j left join public.journal_effective_sources s on s.journal_entry_id=j.id where j.status='posted') select count(*) into v_orphan_cash from eff e where e.effective_type='cash_entry' and not exists(select 1 from public.cash_entries c where c.id=e.effective_id);
  with x as (select c.id,c.balance,coalesce(sum(cl.debit-cl.credit),0) ledger_balance from public.customers c left join public.customer_ledger cl on cl.customer_id=c.id group by c.id,c.balance) select count(*) into v_customer_mismatch from x where abs(balance-ledger_balance)>.01;
  select count(*) into v_secdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prosecdef and (has_function_privilege('public',p.oid,'EXECUTE') or has_function_privilege('anon',p.oid,'EXECUTE'));
  select count(*) into v_catalog_write from pg_policies where schemaname='public' and tablename in ('products','services','categories','brands','units') and cmd in ('INSERT','UPDATE','DELETE','ALL') and exists(select 1 from unnest(roles) x(role_name) where x.role_name='authenticated') and (coalesce(qual,'')='true' or coalesce(with_check,'')='true');
  select count(*) into v_cash_mutation from pg_policies where schemaname='public' and tablename='cash_entries' and cmd in ('UPDATE','DELETE','ALL');
  select count(*) into v_rls_gap from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('products','services','categories','brands','units','cash_entries','customers','payment_instruments','journal_entries','journal_lines') and not c.relrowsecurity;
  v_expected:=coalesce((v_pool->'cash'->>'opening')::numeric,0)+coalesce((v_pool->'cash'->>'movements')::numeric,0); v_actual:=coalesce((v_pool->'cash'->>'current')::numeric,0);
  insert into public.audit_runs(id,run_date,triggered_by,total_checks,passed_count,warning_count,failed_count,critical_count,duration_ms,overall_score) values(v_run,now(),p_triggered_by,0,0,0,0,0,0,100);
  for chk in select * from (values
    ('pool_cash','financial_pool',abs(v_expected-v_actual)<=.01,'HIGH',v_actual,v_expected::text,v_actual::text,abs(v_expected-v_actual),'Cash pool reconciliation','Opening + Net Movements = Current Cash'),
    ('bank_dual_derivation','financial_pool',(not v_bank_seed_exists) or abs(v_bank_life-v_bank_anchor)<=.01,'CRITICAL',v_bank_life,v_bank_life::text,v_bank_anchor::text,abs(v_bank_life-v_bank_anchor),'Bank inception and live anchor agreement','Inception Derivation = Live Bank'),
    ('inventory_stock','financial_pool',v_neg=0,'HIGH',v_neg,'0',v_neg::text,v_neg,'Live inventory non-negative check','Stock >= 0'),
    ('pnl_live','accounting_tax',coalesce((v_pnl->>'unverified_cost_count')::int,0)=0,'LOW',coalesce((v_pnl->>'net_profit')::numeric,0),'0 unverified costs',coalesce((v_pnl->>'unverified_cost_count')::text,'0'),0,'P&L sourced from live get_pnl()','Revenue - Returns + Commission - COGS - Expenses = Net Profit'),
    ('security_immutability','security_governance',v_trigger>=2,'HIGH',v_trigger,'2',v_trigger::text,greatest(0,2-v_trigger),'Invoice tax immutability triggers verified','Required triggers active'),
    ('posted_journal_balance','accounting_integrity',v_unbalanced=0,'CRITICAL',v_unbalanced,'0',v_unbalanced::text,v_unbalanced,'All posted journal entries are balanced','Sum(Debit) = Sum(Credit)'),
    ('orphan_invoice_journals','accounting_integrity',v_orphan_invoice=0,'CRITICAL',v_orphan_invoice,'0',v_orphan_invoice::text,v_orphan_invoice,'No posted invoice journals point to missing invoices','Posted invoice journal source must exist'),
    ('orphan_cash_journals','accounting_integrity',v_orphan_cash=0,'CRITICAL',v_orphan_cash,'0',v_orphan_cash::text,v_orphan_cash,'No posted cash-entry journals point to missing cash entries','Posted cash journal source must exist'),
    ('customer_ledger_reconciliation','ledger_integrity',v_customer_mismatch=0,'HIGH',v_customer_mismatch,'0',v_customer_mismatch::text,v_customer_mismatch,'Customer balances agree with customer-ledger net positions','Customer Balance = Sum(Debit - Credit)'),
    ('public_security_definer','security_governance',v_secdef=0,'CRITICAL',v_secdef,'0',v_secdef::text,v_secdef,'No SECURITY DEFINER function is executable by PUBLIC or anon','PUBLIC/anon EXECUTE on SECURITY DEFINER = 0'),
    ('catalog_write_policy','security_governance',v_catalog_write=0,'CRITICAL',v_catalog_write,'0',v_catalog_write::text,v_catalog_write,'Catalog writes are not broadly open to every authenticated user','Authenticated unguarded catalog write policies = 0'),
    ('cash_mutation_policy','security_governance',v_cash_mutation=0,'CRITICAL',v_cash_mutation,'0',v_cash_mutation::text,v_cash_mutation,'Cash entries have no direct UPDATE/DELETE RLS policy','Direct cash UPDATE/DELETE policies = 0'),
    ('sensitive_rls','security_governance',v_rls_gap=0,'CRITICAL',v_rls_gap,'0',v_rls_gap::text,v_rls_gap,'Sensitive financial/catalog tables have RLS enabled','RLS enabled on all protected tables')
  ) as t(check_id,category,ok,severity,amount,expected_value,actual_value,variance,description,formula) loop
    if chk.ok then v_pass:=v_pass+1; else if chk.severity='CRITICAL' then v_crit:=v_crit+1; elsif chk.severity='HIGH' then v_fail:=v_fail+1; else v_warn:=v_warn+1; end if; end if;
    insert into public.audit_findings(run_id,check_id,category,severity,status,amount,expected_value,actual_value,variance,description,formula) values(v_run,chk.check_id,chk.category,case when chk.ok then 'LOW' else chk.severity end,case when chk.ok then 'PASS' else case when chk.severity='CRITICAL' then 'CRITICAL' when chk.severity='HIGH' then 'FAIL' else 'WARNING' end end,chk.amount,chk.expected_value,chk.actual_value,chk.variance,chk.description,chk.formula);
  end loop;
  update public.audit_runs set total_checks=v_pass+v_fail+v_warn+v_crit,passed_count=v_pass,warning_count=v_warn,failed_count=v_fail,critical_count=v_crit,duration_ms=floor(extract(epoch from(clock_timestamp()-v_start))*1000),overall_score=case when v_crit>0 then 50 when v_fail>0 then 75 when v_warn>0 then 95 else 100 end where id=v_run;
  select jsonb_agg(to_jsonb(f) order by case f.status when 'CRITICAL' then 1 when 'FAIL' then 2 when 'WARNING' then 3 else 4 end) into v_findings from public.audit_findings f where f.run_id=v_run;
  return jsonb_build_object('run_id',v_run,'run_date',now(),'triggered_by',p_triggered_by,'total_checks',v_pass+v_fail+v_warn+v_crit,'passed_count',v_pass,'warning_count',v_warn,'failed_count',v_fail,'critical_count',v_crit,'overall_score',case when v_crit>0 then 50 when v_fail>0 then 75 when v_warn>0 then 95 else 100 end,'duration_ms',floor(extract(epoch from(clock_timestamp()-v_start))*1000),'findings',v_findings);
end; $function$;
