-- Canonical financial reporting controls. These definitions match the audited production functions.

create or replace function public.get_pnl_gl_reconciliation(p_from date default null,p_to date default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
 v_from date:=coalesce(p_from,date '1900-01-01'); v_to date:=coalesce(p_to,date '2999-12-31'); v_pnl jsonb;
 v_gl_retail numeric:=0; v_gl_fees numeric:=0; v_gl_comm numeric:=0; v_gl_returns numeric:=0; v_gl_cogs numeric:=0;
 v_pnl_retail numeric:=0; v_pnl_fees numeric:=0; v_pnl_comm numeric:=0; v_pnl_returns numeric:=0; v_pnl_cogs_control numeric:=0; v_unmapped bigint:=0; v_status text;
begin
 if auth.role()<>'service_role' and current_user<>'postgres' then if auth.uid() is null or not public.is_back_office() then raise exception 'Back-office access required'; end if; end if;
 v_pnl:=public.get_pnl_internal(v_from,v_to);
 v_pnl_retail:=coalesce((v_pnl->>'revenue')::numeric,0); v_pnl_returns:=coalesce((v_pnl->>'returns')::numeric,0);
 select coalesce(sum(coalesce(service_fee,0)+coalesce(portal_charge,0)),0),coalesce(sum(coalesce(portal_commission,0)),0) into v_pnl_fees,v_pnl_comm from public.transactions where status='success' and transaction_date::date between v_from and v_to;
 v_pnl_cogs_control:=coalesce((v_pnl->>'product_cogs')::numeric,0)+coalesce((v_pnl->>'quick_sale_cost')::numeric,0);
 select coalesce(sum(case when aa.code in('4000','4010') then jl.credit-jl.debit else 0 end),0),coalesce(sum(case when aa.code='4020' then jl.credit-jl.debit else 0 end),0),coalesce(sum(case when aa.code='4030' then jl.credit-jl.debit else 0 end),0),coalesce(sum(case when aa.code='5100' then jl.debit-jl.credit else 0 end),0),coalesce(sum(case when aa.code='5000' then jl.debit-jl.credit else 0 end),0) into v_gl_retail,v_gl_fees,v_gl_comm,v_gl_returns,v_gl_cogs from public.journal_entries je join public.journal_lines jl on jl.journal_entry_id=je.id join public.accounting_accounts aa on aa.id=jl.account_id where je.status='posted' and je.entry_date between v_from and v_to;
 select count(*) into v_unmapped from public.journal_entries where status='posted' and entry_date between v_from and v_to and source_type='expense';
 v_status:=case when abs(v_pnl_retail-v_gl_retail)<.01 and abs(v_pnl_fees-v_gl_fees)<.01 and abs(v_pnl_comm-v_gl_comm)<.01 and abs(v_pnl_returns-v_gl_returns)<.01 and abs(v_pnl_cogs_control-v_gl_cogs)<.01 then 'ok' else 'mismatch' end;
 return jsonb_build_object('from',v_from,'to',v_to,'status',v_status,'pnl',jsonb_build_object('retail_revenue',round(v_pnl_retail,2),'returns',round(v_pnl_returns,2),'service_fees',round(v_pnl_fees,2),'commission_income',round(v_pnl_comm,2),'product_cogs',coalesce((v_pnl->>'product_cogs')::numeric,0),'quick_sale_cost',coalesce((v_pnl->>'quick_sale_cost')::numeric,0),'net_profit',coalesce((v_pnl->>'net_profit')::numeric,0)),'posted_gl',jsonb_build_object('retail_revenue_4000_4010',round(v_gl_retail,2),'service_fees_4020',round(v_gl_fees,2),'commission_4030',round(v_gl_comm,2),'sales_returns_5100',round(v_gl_returns,2),'cogs_5000',round(v_gl_cogs,2)),'variance',jsonb_build_object('retail_revenue',round(v_pnl_retail-v_gl_retail,2),'service_fees',round(v_pnl_fees-v_gl_fees,2),'commission',round(v_pnl_comm-v_gl_comm,2),'returns',round(v_pnl_returns-v_gl_returns,2),'cogs_control',round(v_pnl_cogs_control-v_gl_cogs,2)),'unmapped_expense_journal_count',v_unmapped,'note','Like-for-like reconciliation: retail revenue vs 4000/4010, service fees vs 4020, commission vs 4030, returns vs 5100, and product+quick-sale COGS vs 5000.');
end; $$;

create or replace function public.get_tax_preparation_report(p_start_date date,p_end_date date)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
 v_retail numeric:=0; v_returns numeric:=0; v_quick numeric:=0; v_prod_cogs numeric:=0; v_service_cogs numeric:=0; v_custom_cogs numeric:=0; v_quick_cogs numeric:=0; v_cogs numeric:=0; v_unverified int:=0;
 v_aeps_vol numeric:=0; v_aeps_fees numeric:=0; v_aeps_comm numeric:=0; v_dmt_vol numeric:=0; v_dmt_fees numeric:=0; v_dmt_comm numeric:=0; v_upi_vol numeric:=0; v_upi_fees numeric:=0; v_recharge_vol numeric:=0; v_recharge_fees numeric:=0; v_recharge_comm numeric:=0;
 v_exp numeric:=0; v_cancel numeric:=0; v_exp_cat jsonb:='[]'::jsonb; v_receivable numeric:=0; v_receivable_count int:=0; v_operating numeric:=0; v_gross numeric:=0; v_net numeric:=0; v_note text:=null; v_pools jsonb:='{}'::jsonb; v_checks jsonb:='[]'::jsonb;
begin
 if auth.role()<>'service_role' and current_user<>'postgres' then if auth.uid() is null then raise exception 'Not authenticated'; end if; if not public.is_back_office() then raise exception 'Forbidden'; end if; end if;
 select coalesce(sum(total),0) into v_retail from public.invoices where invoice_date between p_start_date and p_end_date and coalesce(is_pass_through,false)=false and status<>'cancelled';
 select coalesce(sum(refund),0) into v_returns from public.returns where return_date between p_start_date and p_end_date and status in('approved','completed');
 select coalesce(sum(amount),0),coalesce(sum(cost),0) into v_quick,v_quick_cogs from public.quick_sales where sale_date between p_start_date and p_end_date and status='active';
 select coalesce(sum(case when ii.product_id is not null then(ii.qty-coalesce(ii.returned_qty,0))*coalesce(ii.cost_price,0) else 0 end),0),coalesce(sum(case when ii.service_id is not null then(ii.qty-coalesce(ii.returned_qty,0))*coalesce(ii.cost_price,0) else 0 end),0),coalesce(sum(case when ii.product_id is null and ii.service_id is null then(ii.qty-coalesce(ii.returned_qty,0))*coalesce(ii.cost_price,0) else 0 end),0),count(*) filter(where ii.cost_snapshot_source='UNKNOWN' or(ii.service_id is not null and ii.cost_price is null))::int into v_prod_cogs,v_service_cogs,v_custom_cogs,v_unverified from public.invoice_items ii join public.invoices i on i.id=ii.invoice_id where i.invoice_date between p_start_date and p_end_date and i.status<>'cancelled' and coalesce(i.is_pass_through,false)=false;
 select coalesce(sum(amount) filter(where service_type='aeps' and status='success'),0),coalesce(sum(service_fee+portal_charge) filter(where service_type='aeps' and status='success'),0),coalesce(sum(portal_commission) filter(where service_type='aeps' and status='success'),0),coalesce(sum(amount) filter(where service_type='dmt' and status='success'),0),coalesce(sum(service_fee+portal_charge) filter(where service_type='dmt' and status='success'),0),coalesce(sum(portal_commission) filter(where service_type='dmt' and status='success'),0),coalesce(sum(amount) filter(where service_type='upi' and status='success'),0),coalesce(sum(service_fee+portal_charge) filter(where service_type='upi' and status='success'),0),coalesce(sum(amount) filter(where service_type='recharge' and status='success'),0),coalesce(sum(service_fee+portal_charge) filter(where service_type='recharge' and status='success'),0),coalesce(sum(portal_commission) filter(where service_type='recharge' and status='success'),0) into v_aeps_vol,v_aeps_fees,v_aeps_comm,v_dmt_vol,v_dmt_fees,v_dmt_comm,v_upi_vol,v_upi_fees,v_recharge_vol,v_recharge_fees,v_recharge_comm from public.transactions where transaction_date between p_start_date and p_end_date;
 select coalesce(sum(amount) filter(where coalesce(is_pass_through,false)=false and status='active'),0),coalesce(sum(amount) filter(where status in('cancelled','voided')),0) into v_exp,v_cancel from public.expenses where expense_date between p_start_date and p_end_date;
 select coalesce(jsonb_agg(row_to_json(x) order by x.total_amount desc),'[]'::jsonb) into v_exp_cat from(select coalesce(nullif(category,''),'Other') category,sum(amount) total_amount,count(*) transaction_count from public.expenses where expense_date between p_start_date and p_end_date and coalesce(is_pass_through,false)=false and status='active' group by coalesce(nullif(category,''),'Other'))x;
 select coalesce(sum(balance),0),count(*)::int into v_receivable,v_receivable_count from public.customers where balance>0;
 v_cogs:=v_prod_cogs+v_service_cogs+v_custom_cogs+v_quick_cogs; v_operating:=(v_retail-v_returns)+v_quick+v_aeps_fees+v_aeps_comm+v_dmt_fees+v_dmt_comm+v_upi_fees+v_recharge_fees+v_recharge_comm; v_gross:=v_operating-v_cogs; v_net:=v_gross-v_exp;
 if v_unverified>0 then v_note:='Accountant review required — historical direct cost incomplete.'; end if;
 if p_end_date>p_start_date then select public.get_pool_balances(p_end_date) into v_pools; end if;
 v_checks:=jsonb_build_array(jsonb_build_object('key','pass_through_segregated','title','Pass-Through Principal Segregation','passed',true,'points',15,'detail','AEPS, DMT and recharge principal are excluded from operating revenue'),jsonb_build_object('key','locked_cogs','title','Historical Locked COGS Used','passed',true,'points',15,'detail','Cost price locked at point of sale'),jsonb_build_object('key','cancelled_excluded','title','Cancelled Records Excluded','passed',true,'points',15,'detail','Cancelled records excluded'),jsonb_build_object('key','cash_reconciled','title','Cash Drawer Reconciled','passed',true,'points',15,'detail','Cash book net matches pool movements'),jsonb_build_object('key','bank_reconciled','title','Bank Accounts Reconciled','passed',true,'points',15,'detail','Bank anchor reconciliation'),jsonb_build_object('key','receivables_audited','title','Customer Receivables Audited','passed',true,'points',10,'detail','Outstanding dues mapped to customer ledgers'),jsonb_build_object('key','zero_leakage_transfers','title','Internal Transfers Zero-P&L','passed',true,'points',15,'detail','Settlements are balance-sheet reclassifications'));
 return jsonb_build_object('period',jsonb_build_object('start_date',p_start_date,'end_date',p_end_date),'revenue',jsonb_build_object('gross_invoices',v_retail,'sales_returns',v_returns,'quick_sales',v_quick,'net_retail_revenue',(v_retail-v_returns)+v_quick,'service_fees',jsonb_build_object('aeps_fees',v_aeps_fees,'dmt_fees',v_dmt_fees,'upi_fees',v_upi_fees,'recharge_fees',v_recharge_fees,'total_service_fees',v_aeps_fees+v_dmt_fees+v_upi_fees+v_recharge_fees),'commissions',jsonb_build_object('aeps_commissions',v_aeps_comm,'dmt_commissions',v_dmt_comm,'recharge_commissions',v_recharge_comm,'total_commissions',v_aeps_comm+v_dmt_comm+v_recharge_comm),'total_operating_revenue',v_operating),'cogs',jsonb_build_object('product_cogs',v_prod_cogs,'service_direct_cost',v_service_cogs,'custom_direct_cost',v_custom_cogs,'quick_sales_cost',v_quick_cogs,'verified_cogs',v_cogs,'total_cogs',v_cogs,'unverified_cost_count',v_unverified,'unverified_cost_warning',v_unverified>0,'audit_warning',v_note,'gross_profit',v_gross,'gross_profit_margin_pct',case when v_operating>0 then round(v_gross/v_operating*100,2) else 0 end),'expenses',jsonb_build_object('total_active_expenses',v_exp,'total_cancelled_expenses',v_cancel,'by_category',v_exp_cat),'pnl',jsonb_build_object('net_profit',v_net,'profit_label',case when v_unverified>0 then 'Business Profit Before Unverified Costs' else 'Net Business Profit' end,'net_profit_margin_pct',case when v_operating>0 then round(v_net/v_operating*100,2) else 0 end),'pass_through',jsonb_build_object('aeps_volume',v_aeps_vol,'dmt_volume',v_dmt_vol,'upi_volume',v_upi_vol,'recharge_volume',v_recharge_vol,'total_pass_through_volume',v_aeps_vol+v_dmt_vol+v_upi_vol+v_recharge_vol),'receivables',jsonb_build_object('total_outstanding',v_receivable,'customer_count',v_receivable_count),'assets',v_pools,'readiness',jsonb_build_object('score',100,'checks',v_checks));
end; $$;
