create or replace function public.get_gst_pnl_journal_reconciliation(p_from date default null, p_to date default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
 v_from date:=coalesce(p_from,date '1900-01-01'); v_to date:=coalesce(p_to,date '2999-12-31');
 v_output_gst numeric:=0; v_output_reversal numeric:=0; v_input_gst numeric:=0; v_input_reversal numeric:=0;
 v_output_journal numeric:=0; v_input_journal numeric:=0; v_revenue numeric:=0; v_returns numeric:=0; v_cogs numeric:=0; v_expenses numeric:=0; v_commission numeric:=0;
 v_net_output numeric:=0; v_net_input numeric:=0; v_net_gst numeric:=0; v_journal_net_gst numeric:=0; v_output_variance numeric:=0; v_input_variance numeric:=0; v_net_tax_variance numeric:=0; v_pnl_net numeric:=0;
begin
 if auth.role()<>'service_role' and current_user<>'postgres' then if auth.uid() is null then raise exception 'Not authenticated'; end if; if not public.is_back_office() then raise exception 'Back-office access required'; end if; end if;
 select coalesce(sum(i.total_cgst+i.total_sgst+i.total_igst),0) into v_output_gst from invoices i where i.invoice_date between v_from and v_to and i.status<>'cancelled';
 select coalesce(sum(coalesce(r.cgst_reversed,0)+coalesce(r.sgst_reversed,0)+coalesce(r.igst_reversed,0)),0) into v_output_reversal from returns r join invoices i on i.id=r.invoice_id where r.return_date between v_from and v_to and r.status in ('completed','approved') and i.status<>'cancelled';
 select coalesce(sum(pi.tax_amount),0) into v_input_gst from purchase_items pi join purchases p on p.id=pi.purchase_id where p.purchase_date between v_from and v_to and p.status<>'cancelled';
 select coalesce(sum(jl.debit),0) into v_input_reversal from journal_entries je join journal_lines jl on jl.journal_entry_id=je.id join accounting_accounts aa on aa.id=jl.account_id where je.entry_date between v_from and v_to and je.status='posted' and je.source_type='purchase_return_tax' and aa.code='2000';
 select coalesce(sum(jl.credit-jl.debit),0) into v_output_journal from journal_entries je join journal_lines jl on jl.journal_entry_id=je.id join accounting_accounts aa on aa.id=jl.account_id where je.entry_date between v_from and v_to and je.status='posted' and aa.code='2100';
 select coalesce(sum(jl.debit-jl.credit),0) into v_input_journal from journal_entries je join journal_lines jl on jl.journal_entry_id=je.id join accounting_accounts aa on aa.id=jl.account_id where je.entry_date between v_from and v_to and je.status='posted' and aa.code='2200';
 select coalesce(sum(i.total),0) into v_revenue from invoices i where i.invoice_date between v_from and v_to and i.status<>'cancelled' and coalesce(i.is_pass_through,false)=false;
 select coalesce(sum(r.subtotal),0) into v_returns from returns r join invoices i on i.id=r.invoice_id where r.return_date between v_from and v_to and r.status='completed' and i.status<>'cancelled' and coalesce(i.is_pass_through,false)=false;
 select coalesce(sum((ii.qty-coalesce(ii.returned_qty,0))*coalesce(ii.cost_price,0)),0) into v_cogs from invoice_items ii join invoices i on i.id=ii.invoice_id where i.invoice_date between v_from and v_to and i.status<>'cancelled' and coalesce(i.is_pass_through,false)=false;
 select coalesce(sum(e.amount),0) into v_expenses from expenses e where e.expense_date between v_from and v_to and e.status='active' and coalesce(e.is_pass_through,false)=false;
 select coalesce(sum(coalesce(t.portal_commission,t.commission,0)+coalesce(t.service_fee,0)),0) into v_commission from transactions t where t.status='success' and t.transaction_date::date between v_from and v_to;
 v_net_output:=round(v_output_gst-v_output_reversal,2); v_net_input:=round(v_input_gst-v_input_reversal,2); v_net_gst:=round(v_net_output-v_net_input,2); v_journal_net_gst:=round(v_output_journal-v_input_journal,2); v_output_variance:=round(v_net_output-v_output_journal,2); v_input_variance:=round(v_net_input-v_input_journal,2); v_net_tax_variance:=round(v_net_gst-v_journal_net_gst,2); v_pnl_net:=round(v_revenue-v_returns-v_cogs-v_expenses+v_commission,2);
 return jsonb_build_object('from',v_from,'to',v_to,'gst',jsonb_build_object('output_gst',round(v_output_gst,2),'output_reversal',round(v_output_reversal,2),'net_output_gst',v_net_output,'input_gst',round(v_input_gst,2),'input_reversal',round(v_input_reversal,2),'net_input_gst',v_net_input,'net_gst_payable_before_credits',v_net_gst),'journals',jsonb_build_object('output_gst_account_2100',round(v_output_journal,2),'input_gst_account_2200',round(v_input_journal,2),'net_tax_position',v_journal_net_gst),'pnl',jsonb_build_object('revenue',round(v_revenue,2),'returns',round(v_returns,2),'cogs',round(v_cogs,2),'expenses',round(v_expenses,2),'commission',round(v_commission,2),'net_profit_before_tax',v_pnl_net),'variance',jsonb_build_object('output',v_output_variance,'input',v_input_variance,'net_tax',v_net_tax_variance),'status',case when abs(v_output_variance)<0.01 and abs(v_input_variance)<0.01 and abs(v_net_tax_variance)<0.01 then 'ok' else 'mismatch' end,'note','GST control accounts 2100/2200 are reconciled to source tax documents; GST is not treated as P&L revenue or expense.');
end; $$;
grant execute on function public.get_gst_pnl_journal_reconciliation(date,date) to authenticated;
